import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/theme/app_theme.dart';
import '../../data/erp_providers.dart';
import '../../data/erp_repository.dart';
import '../../models/user_model.dart';
import '../auth/auth_service.dart';
import '../student/student_detail_screen.dart';

/// Teacher/Admin: mark attendance by class with holiday option and mark-all-present.
class TeacherAttendanceScreen extends ConsumerStatefulWidget {
  const TeacherAttendanceScreen({super.key});

  @override
  ConsumerState<TeacherAttendanceScreen> createState() => _TeacherAttendanceScreenState();
}

class _TeacherAttendanceScreenState extends ConsumerState<TeacherAttendanceScreen> {
  int _classLevel = 8;
  DateTime _date = DateTime.now();
  bool _isHoliday = false;
  final _holidayMsg = TextEditingController();
  final Map<String, bool> _present = {};
  List<StudentListItem> _students = [];
  bool _loading = true;
  bool _saving = false;
  bool _attendanceJustSaved = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _holidayMsg.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _attendanceJustSaved = false;
    });
    final repo = ref.read(erpRepositoryProvider);
    try {
      final list = await repo.fetchStudentsByClass(_classLevel);
      final existing = await repo.getAttendanceForDay(_classLevel, _date);
      final map = <String, bool>{for (final s in list) s.roll: true};
      if (existing != null) {
        _isHoliday = existing['isHoliday'] == true;
        _holidayMsg.text = (existing['holidayMessage'] ?? '').toString();
        if (!_isHoliday && existing['records'] is Map) {
          final r = Map<String, dynamic>.from(existing['records'] as Map);
          for (final s in list) {
            map[s.roll] = r[s.roll] == true;
          }
        }
      }
      setState(() {
        _students = list;
        _present
          ..clear()
          ..addAll(map);
      });
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _save() async {
    final user = ref.read(authProvider);
    if (user == null || !user.isStaff || user.email == null) return;

    setState(() => _saving = true);
    try {
      await ref.read(erpRepositoryProvider).saveAttendance(
            classLevel: _classLevel,
            date: DateTime(_date.year, _date.month, _date.day),
            isHoliday: _isHoliday,
            holidayMessage: _holidayMsg.text.trim().isEmpty ? null : _holidayMsg.text.trim(),
            presentByRoll: Map<String, bool>.from(_present),
            savedByEmail: user.email!,
          );
      // Update current homework date if different
      final currentHomeworkDate = ref.read(currentHomeworkDateProvider);
      if (!DateUtils.isSameDay(currentHomeworkDate, _date)) {
        ref.read(currentHomeworkDateProvider.notifier).setDate(_date);
      }
      if (mounted) {
        setState(() => _attendanceJustSaved = true);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Attendance saved. Share with group?')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  String _generateAttendanceReport() {
    final dateFormatter = DateFormat('dd/MM/yyyy');
    final dateStr = dateFormatter.format(_date);
    
    final presentStudents = <String>[];
    final absentStudents = <String>[];

    for (final s in _students) {
      if (_present[s.roll] == true) {
        presentStudents.add(s.name);
      } else {
        absentStudents.add(s.name);
      }
    }

    // Sort lists alphabetically
    presentStudents.sort();
    absentStudents.sort();

    // Format message according to specification
    String report = '🔴 *Mentor Classes - Daily Attendance Report* 🔴\n\n';
    report += '📅 *Date:* $dateStr\n';
    report += '📖 *Class:* Class $_classLevel\n\n';
    
    report += '✅ *PRESENT STUDENTS:*\n';
    if (presentStudents.isEmpty) {
      report += '• None\n';
    } else {
      for (var i = 0; i < presentStudents.length; i++) {
        report += '${i + 1}. ${presentStudents[i]}\n';
      }
    }
    
    report += '\n🚫 *ABSENT STUDENTS:*\n';
    if (absentStudents.isEmpty) {
      report += '• None\n';
    } else {
      for (var i = 0; i < absentStudents.length; i++) {
        report += '${i + 1}. ${absentStudents[i]}\n';
      }
    }
    
    report += '\n📊 *Summary:* Total Present: ${presentStudents.length} | Total Absent: ${absentStudents.length}\n';
    report += '\n_Report Generated by: Mentor Classes ERP_';

    return report;
  }

  Future<void> _shareToWhatsAppGroup() async {
    final report = _generateAttendanceReport();
    final encoded = Uri.encodeComponent(report);
    
    // Launch WhatsApp with contact picker - user manually selects coaching group
    final whatsappAppUrl = Uri.parse('whatsapp://send?text=$encoded');
    final whatsappWebUrl = Uri.parse('https://wa.me/?text=$encoded');

    try {
      if (await canLaunchUrl(whatsappAppUrl)) {
        // WhatsApp app is installed - will show contact picker
        await launchUrl(whatsappAppUrl, mode: LaunchMode.externalApplication);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('✅ Select your Coaching Group to send the attendance report'),
              duration: Duration(seconds: 3),
            ),
          );
        }
      } else if (await canLaunchUrl(whatsappWebUrl)) {
        // Fallback to web WhatsApp
        await launchUrl(whatsappWebUrl, mode: LaunchMode.externalApplication);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('✅ Web WhatsApp opened - select your Coaching Group'),
              duration: Duration(seconds: 3),
            ),
          );
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('❌ WhatsApp not installed. Install WhatsApp to share attendance reports.'),
              duration: Duration(seconds: 3),
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('⚠️ Error: $e'),
            duration: const Duration(seconds: 2),
          ),
        );
      }
    }
  }

  Future<void> _showShareOptions() async {
    showModalBottomSheet(
      context: context,
      builder: (context) => Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              'Share Attendance Report',
              style: GoogleFonts.poppins(fontWeight: FontWeight.w600, fontSize: 16),
            ),
            const SizedBox(height: 8),
            Text(
              'Send formatted attendance report to WhatsApp group',
              style: GoogleFonts.poppins(fontSize: 12, color: Colors.grey.shade600),
            ),
            const SizedBox(height: 16),
            ListTile(
              leading: const Icon(Icons.share, color: Color(0xFF25D366)),
              title: const Text('Share to Coaching Group'),
              subtitle: Text('Complete attendance for Class $_classLevel', 
                  style: GoogleFonts.poppins(fontSize: 12, color: Colors.grey.shade600)),
              trailing: const Icon(Icons.arrow_forward, size: 18),
              onTap: () {
                Navigator.pop(context);
                _shareToWhatsAppGroup();
              },
            ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.blue.shade50,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  Icon(Icons.info_outline, size: 18, color: Colors.blue.shade700),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'WhatsApp will open. Manually select your Coaching Group to send the report.',
                      style: GoogleFonts.poppins(fontSize: 11, color: Colors.blue.shade700),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final df = DateFormat.yMMMd();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
          child: Card(
            elevation: 0,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(14),
              side: BorderSide(color: Colors.grey.shade200),
            ),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Class & date', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, color: AppTheme.deepBlue)),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: DropdownButtonFormField<int>(
                          // ignore: deprecated_member_use
                          value: _classLevel,
                          decoration: const InputDecoration(labelText: 'Class'),
                          items: [
                            for (var c = StudentClassLevels.min; c <= StudentClassLevels.max; c++)
                              DropdownMenuItem(value: c, child: Text('Class $c')),
                          ],
                          onChanged: (v) {
                            if (v == null) return;
                            setState(() => _classLevel = v);
                            _load();
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: OutlinedButton.icon(
                          onPressed: () async {
                            final picked = await showDatePicker(
                              context: context,
                              initialDate: _date,
                              firstDate: DateTime(2024),
                              lastDate: DateTime(2035),
                            );
                            if (picked != null) {
                              setState(() => _date = picked);
                              _load();
                            }
                          },
                          icon: const Icon(Icons.calendar_today, size: 18),
                          label: Text(df.format(_date), style: GoogleFonts.poppins(fontSize: 13)),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  SwitchListTile(
                    contentPadding: EdgeInsets.zero,
                    title: Text('Mark as holiday', style: GoogleFonts.poppins(fontWeight: FontWeight.w500)),
                    subtitle: Text(
                      'Whole day off — no per-student marks.',
                      style: GoogleFonts.poppins(fontSize: 12, color: Colors.grey.shade700),
                    ),
                    value: _isHoliday,
                    activeThumbColor: AppTheme.deepBlue,
                    onChanged: (v) => setState(() => _isHoliday = v),
                  ),
                  if (_isHoliday)
                    TextField(
                      controller: _holidayMsg,
                      decoration: const InputDecoration(
                        labelText: 'Message (e.g. Rain holiday)',
                        hintText: 'Due to rain, class is suspended today.',
                      ),
                      maxLines: 2,
                    ),
                  if (!_isHoliday) ...[
                    const SizedBox(height: 8),
                    FilledButton.tonalIcon(
                      onPressed: _students.isEmpty
                          ? null
                          : () {
                              setState(() {
                                for (final s in _students) {
                                  _present[s.roll] = true;
                                }
                              });
                            },
                      icon: const Icon(Icons.done_all),
                      label: const Text('Mark all present'),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ),
        Expanded(
          child: _loading
              ? const Center(child: CircularProgressIndicator())
              : _isHoliday
                  ? Center(
                      child: Text(
                        'Holiday mode — save to notify parents & post notice.',
                        textAlign: TextAlign.center,
                        style: GoogleFonts.poppins(color: Colors.grey.shade700),
                      ),
                    )
                  : _students.isEmpty
                      ? Center(
                          child: Text(
                            'No students in Class $_classLevel. Upload via Excel first.',
                            textAlign: TextAlign.center,
                            style: GoogleFonts.poppins(color: Colors.grey.shade700),
                          ),
                        )
                      : ListView.builder(
                          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                          itemCount: _students.length,
                          itemBuilder: (context, i) {
                            final s = _students[i];
                            final present = _present[s.roll] ?? true;
                            return Card(
                              margin: const EdgeInsets.only(bottom: 8),
                              elevation: 0,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                                side: BorderSide(color: Colors.grey.shade200),
                              ),
                              child: InkWell(
                                onTap: () {
                                  Navigator.of(context).push(
                                    MaterialPageRoute(
                                      builder: (context) => StudentDetailScreen(
                                        studentDocId: s.docId,
                                        studentName: s.name,
                                        studentRoll: s.roll,
                                      ),
                                    ),
                                  );
                                },
                                child: SwitchListTile(
                                  title: Text(s.name, style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
                                  subtitle: Text('Roll ${s.roll}', style: GoogleFonts.poppins(fontSize: 13)),
                                  value: present,
                                  activeThumbColor: Colors.green.shade700,
                                  inactiveThumbColor: Colors.red.shade300,
                                  onChanged: (v) => setState(() => _present[s.roll] = v),
                                ),
                              ),
                            );
                          },
                        ),
        ),
        Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              FilledButton(
                onPressed: _saving ? null : _save,
                child: _saving
                    ? const SizedBox(
                        height: 22,
                        width: 22,
                        child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                      )
                    : Text('Save attendance', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
              ),
              if (_attendanceJustSaved) ...[
                const SizedBox(height: 12),
                FilledButton.tonalIcon(
                  onPressed: _showShareOptions,
                  icon: const Icon(Icons.share),
                  label: const Text('Share Report to Group'),
                ),
              ],
            ],
          ),
        ),
      ],
    );
  }
}
