# Podfile
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(packages_path, '.symlinks', 'plugins', 'flutter_app_badger', '.dart_tool', 'flutter_build', 'generated_xcode_build_settings.json'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.expand_path(File.join(File.dirname(generated_xcode_build_settings_path), '..', '..', '..', '..'), __FILE__)
end

def load_from_podfile_lock_for(key)
  lock_path = File.join(File.dirname(__FILE__), 'Podfile.lock')
  return nil unless File.exist?(lock_path)
  
  lock_file = File.read(lock_path)
  lock_file.match(/#{key}:\n\s*- (.+)/)[1].strip.split(' ').first if lock_file.match(/#{key}:\n\s*- (.+)/)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
